DROP TABLE IF EXISTS crm.stage;

CREATE TABLE IF NOT EXISTS crm.stage
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stage_name character varying(100) COLLATE pg_catalog."default",
    stage_info text COLLATE pg_catalog."default",
    stage_order integer NOT NULL,
    stage_sub_order integer,
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,

    CONSTRAINT stage_pkey PRIMARY KEY (id),
    CONSTRAINT stage_stage_order_unique UNIQUE (stage_order,stage_sub_order),
    CONSTRAINT stage_stage_order_positive CHECK (stage_order > 0),
    CONSTRAINT stage_stage_sub_order_positive CHECK (stage_sub_order > 0)
)
    TABLESPACE pg_default;

DROP TABLE IF EXISTS crm.smeta;

CREATE TABLE IF NOT EXISTS crm.smeta
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    smeta_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    smeta_info text COLLATE pg_catalog."default",
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    contractor_id bigint,
    CONSTRAINT smeta_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;


DROP TABLE IF EXISTS crm.user;

CREATE TABLE IF NOT EXISTS crm.user
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name character varying(100) COLLATE pg_catalog."default",
    user_login character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_mail character varying(100) COLLATE pg_catalog."default",
    user_phone character varying(20) COLLATE pg_catalog."default",
    is_admin_flg boolean DEFAULT false,
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_login_unique UNIQUE (user_login)
)

    TABLESPACE pg_default;


DROP TABLE IF EXISTS crm.stage_type;

CREATE TABLE IF NOT EXISTS crm.stage_type
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stage_type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    stage_type_info text COLLATE pg_catalog."default",
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    CONSTRAINT stage_type_pkey PRIMARY KEY (id),
    CONSTRAINT stage_type_name_unique UNIQUE (stage_type_name)
)

    TABLESPACE pg_default;


DROP TABLE IF EXISTS crm.contractor;

CREATE TABLE IF NOT EXISTS crm.contractor
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contractor_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    contractor_info text COLLATE pg_catalog."default",
    contractor_mail character varying(100) COLLATE pg_catalog."default",
    contractor_phone_1 character varying(20) COLLATE pg_catalog."default",
    contractor_phone_2 character varying(20) COLLATE pg_catalog."default",
    contractor_phone_3 character varying(20) COLLATE pg_catalog."default",
    contractor_inn character varying(20) COLLATE pg_catalog."default",
    contractor_passport_number character varying(20) COLLATE pg_catalog."default",
    contractor_passport_series character varying(20) COLLATE pg_catalog."default",
    contractor_passport_code character varying(20) COLLATE pg_catalog."default",
    contractor_passport_issue_place character varying(255) COLLATE pg_catalog."default",
    contractor_passport_issue_date date,
    contractor_address text COLLATE pg_catalog."default",
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    contractor_type_id bigint,
    CONSTRAINT contractor_pkey PRIMARY KEY (id),
    CONSTRAINT contractor_name_unique UNIQUE (contractor_name)
)

    TABLESPACE pg_default;




DROP TABLE IF EXISTS crm.contractor_type;

CREATE TABLE IF NOT EXISTS crm.contractor_type
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contractor_type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contractor_type_info text COLLATE pg_catalog."default",
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    CONSTRAINT contractor_type_pkey PRIMARY KEY (id),
    CONSTRAINT contractor_type_name_unique UNIQUE (contractor_type_name)
)

    TABLESPACE pg_default;



DROP TABLE IF EXISTS crm.position_type;

CREATE TABLE IF NOT EXISTS crm.position_type
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position_type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    position_type_info text COLLATE pg_catalog."default",
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    CONSTRAINT position_type_pkey PRIMARY KEY (id),
    CONSTRAINT position_type_name_unique UNIQUE (position_type_name)
)

    TABLESPACE pg_default;



DROP TABLE IF EXISTS crm.link_smeta_stage;

CREATE TABLE IF NOT EXISTS crm.link_smeta_stage
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    smeta_id bigint NOT NULL,
    stage_id bigint NOT NULL,
    stage_order integer NOT NULL,
    stage_type_id bigint,
    create_dttm timestamp without time zone NOT NULL DEFAULT now(),
    update_dttm timestamp without time zone NOT NULL DEFAULT now(),
    create_user_id bigint NOT NULL DEFAULT 1,
    update_user_id bigint NOT NULL DEFAULT 1,
    CONSTRAINT link_smeta_stage_pkey PRIMARY KEY (id),
    CONSTRAINT smeta_stage_unique UNIQUE (smeta_id,stage_id),
    CONSTRAINT smeta_stage_order_unique UNIQUE (smeta_id,stage_order)

)

    TABLESPACE pg_default;


DROP TABLE IF EXISTS crm.link_stage_position;

CREATE TABLE IF NOT EXISTS crm.link_stage_position
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stage_id bigint NOT NULL,
    position_id bigint NOT NULL,
    position_amount NUMERIC(12,0),
    position_sum NUMERIC(6,2),
    position_count integer,
    provider_id bigint,
    position_order integer,
    create_dttm timestamp without time zone NOT NULL DEFAULT now(),
    update_dttm timestamp without time zone NOT NULL DEFAULT now(),
    create_user_id bigint NOT NULL DEFAULT 1,
    update_user_id bigint NOT NULL DEFAULT 1,
    CONSTRAINT link_stage_position_pkey PRIMARY KEY (id),
    CONSTRAINT stage_position_unique UNIQUE (stage_id,position_id)

)

    TABLESPACE pg_default;



DROP TABLE IF EXISTS crm.position;

CREATE TABLE IF NOT EXISTS crm.position
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position_name character varying(255) COLLATE pg_catalog."default",
    position_info text COLLATE pg_catalog."default",
    position_type_id bigint NOT NULL,
    stage_id bigint,
    position_sum_formula text,
    position_amount_formula text,
    unit_type_id bigint NOT NULL,
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    CONSTRAINT position_pkey PRIMARY KEY (id),
    CONSTRAINT position_name_unique UNIQUE (position_name)
)

    TABLESPACE pg_default;



DROP TABLE IF EXISTS crm.unit_type;

CREATE TABLE IF NOT EXISTS crm.unit_type
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    unit_type_info text COLLATE pg_catalog."default",
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    CONSTRAINT unit_type_pkey PRIMARY KEY (id),
    CONSTRAINT unit_type_name_unique UNIQUE (unit_type_name)
)

    TABLESPACE pg_default;



DROP TABLE IF EXISTS crm.contract;

CREATE TABLE IF NOT EXISTS crm.contract
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_num character varying(50) COLLATE pg_catalog."default" NOT NULL,
    contract_date date NOT NULL,
    contractor_id bigint NOT NULL,
    create_dttm timestamp without time zone DEFAULT now(),
    update_dttm timestamp without time zone DEFAULT now(),
    create_user_id bigint DEFAULT 1,
    update_user_id bigint DEFAULT 1,
    CONSTRAINT contract_pkey PRIMARY KEY (id),
    CONSTRAINT contract_num_unique UNIQUE (contract_num)
)

    TABLESPACE pg_default;




-------------------- Загрузка данных -------------

-- stage_type
INSERT INTO crm.stage_type (stage_type_name)
VALUES
    ('Забивные ЖБ сваи 150х150х3000мм'),
    ('два этажа')
ON CONFLICT (stage_type_name) DO NOTHING;

INSERT INTO crm.contractor_type (contractor_type_name)
VALUES
    ('ФЛ'),
    ('ИП'),
    ('ЮЛ')
ON CONFLICT (contractor_type_name) DO NOTHING;

-- stage
INSERT INTO crm.stage (stage_name, stage_order)
VALUES
    ('Фундамент', 1),
    ('Комплект стен, Лаги, Балки', 2),
    ('Кровля', 3),
    ('Окна двери', 4),
    ('Отделка', 5),
    ('Доставка разгрузка', 6)
ON CONFLICT DO NOTHING;

-- unit_type
INSERT INTO crm.unit_type (unit_type_name)
VALUES
    ('шт.'),
    ('м3'),
    ('10л.'),
    ('м.пог.'),
    ('м2'),
    ('комплект'),
    ('рейс')
ON CONFLICT (unit_type_name) DO NOTHING;

-- position_type
INSERT INTO crm.position_type (position_type_name)
VALUES
    ('Материалы'),
    ('Работы')
ON CONFLICT (position_type_name) DO NOTHING;

-- position

INSERT INTO crm.position (position_name, position_type_id, unit_type_id, stage_id)
VALUES
    ('Забивные ЖБ сваи 150х150х3000мм (с учетом доставки)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Фундамент')),
    ('Брус 200х150мм(обвязка) 18шт.', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Фундамент')),
    ('Сенеж антисептик трудновымываемый для древесины в тяжелых условиях эксплуатации', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = '10л.'), (SELECT id FROM crm.stage WHERE stage_name = 'Фундамент')),
    ('Монтаж Забивных ЖБ сваи 200х200х4000мм', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Фундамент')),
    ('Монтаж обвязки с учетом антисептирования', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м.пог.'), (SELECT id FROM crm.stage WHERE stage_name = 'Фундамент')),
    ('Комплект стен из Клееного бруса 200х180(170мм) 248шт.', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Политерм Стандарт-120(Толщина 6-8 мм)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м.пог.'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Нагеля березовые д25длина 1200мм', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Узел пружинный модернизированный Узел Сила 10x280 мм, 50 шт.', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Расх. Материалы: скобы на стейплер, скобы строительные, ГСМ, компенсаторы.', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Брус 200х50х6000мм первый сорт (Лаги Балки) 76шт', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Брус 200х100х6000мм первый сорт (Лаги Балки) 6шт', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Опора бруса открытая (опора раскрытая) 50х180, стальная оцинкованная', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Сенеж антисептик трудновымываемый для древесины в тяжелых условиях эксплуатации', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = '10л.'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Монтаж комплекта стен из Клееного бруса 200х180(170мм) 248шт.', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Установка Балок и Лаг', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Комплект стен, Лаги, Балки')),
    ('Доска обрезная 50х200 6000мм первый сорт (стропило)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Брусок 150х25 6000мм первый сорт (обрешетка)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Брусок 50х50мм(контр обрешётка)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Мембрана ИЗОСПАН гидро-ветрозащитная AM, 85г/м2 43.75 м 1.6 м', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Расх. Материалы: скобы на стейплер, скользящие опоры, пластины, ГСМ', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Утеплитель Роквул Лайт Баттс Скандик 100х600х800 мм 2,88 кв.м', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Пароизоляция Изоспан B', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Доска 150х25х6000мм (Обрешетка)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Комплект кровельного покрытия металлочерепицы с снегозадержателями и водосточной системой', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Монтаж стропильной конструкции', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Настил гидроизоляции и монтаж контр обрешётки', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Настил обрешетки', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Монтаж металлочерепицы', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Монтаж планок', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Монтаж водосточной системы, снегозадержателей', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Укладка утеплителя', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Настил пароизоляции', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Кровля')),
    ('Доска обрезная 50х200 6000мм строг. камерной сушки', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Брусок 50х50х6000мм строг. камерной сушки', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Комплект: саморезы, Герметик Теплый шов, ГСМ', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Комплект окон и входных дверей; Профиль: Rehau Grazio Уплотнитель: Черный; Подставочный профиль 342: 1 шт.; Фурнитура ROTO NT; Заполнение: 4-10-4-10-4. С односторонней ламинацией и раскладкой', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'комплект'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Доска сух строг. 150х20х6000мм(обналичка окон)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Подоконники', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м.пог.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Дверь межкомнатная глухая Стелла 80x200 см эмаль белый с замком и петлями', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Дверь входная с терморазрывом Mastino Титан правая букле графит - эмаль молоко 960х2050 мм', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Окосячка Оконных и дверных проемов', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Установка ПВХ окон и дверей', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Монтаж обналички и откосов', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м.пог.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Монтаж подоконников', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м.пог.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Монтаж межкомнатных дверей(с обналичкой замками и ручками)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Монтаж входной двери', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Окна двери')),
    ('Доска черного пола,150х25х6000мм(снизу)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Доска сухая строганная 140х25Х6000мм (Сверху)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м3'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Изоспан АМ', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Сетка от грызунов, кротов, мышей, крыс 6х6х0.6 оцинкованная сварная 1х10м (ячейка 6х6 мм d-0.6мм)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Утеплитель Роквул Лайт Баттс Скандик 100х600х800 мм 2,88 кв.м полы потолки', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Расх. материалы', (SELECT id FROM crm.position_type WHERE position_type_name = 'Материалы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'комплект'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Настил чернового пола(снизу)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Настил гидроизоляции полов', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Монтаж сетки от грызунов', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Укладка утеплителя(полов и потолков)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Настил пароизоляции полов', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Настил обрешетки полов (сверху)', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'м2'), (SELECT id FROM crm.stage WHERE stage_name = 'Отделка')),
    ('Доставка в Московскую область комплекта стен', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'рейс'), (SELECT id FROM crm.stage WHERE stage_name = 'Доставка разгрузка')),
    ('Разгрузка и доставка комплекта стен до участка манипулятором', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Доставка разгрузка')),
    ('Доставка Пиломатериала', (SELECT id FROM crm.position_type WHERE position_type_name = 'Работы'), (SELECT id FROM crm.unit_type WHERE unit_type_name = 'шт.'), (SELECT id FROM crm.stage WHERE stage_name = 'Доставка разгрузка'))
ON CONFLICT (position_name) DO NOTHING;



--------------------------------------- Функции

create or replace function crm.check_user_credentials(
    p_login varchar,
    p_password varchar
)
    returns boolean
    language sql
as
$$
select exists (
    select 1
    from crm."user"
    where user_login = p_login
      and user_password = p_password
);
$$;

INSERT INTO crm."user"(
    user_name, user_login, user_password)
VALUES ('test','test','test');

create or replace function crm.fn_select_contract(
    p_id  bigint default null,
    p_lmt integer default null
)
    returns table (
                      id             bigint,
                      contract_num   varchar,
                      contract_date  date,
                      contractor_id  bigint,
                      create_dttm    timestamp,
                      update_dttm    timestamp,
                      create_user_id bigint,
                      update_user_id bigint
                  )
    language plpgsql
as
$$
declare
    v_sql text;
begin
    v_sql := '
        select
            c.id,
            c.contract_num,
            c.contract_date,
            c.contractor_id,
            c.create_dttm,
            c.update_dttm,
            c.create_user_id,
            c.update_user_id
        from crm.contract c
        where 1 = 1
    ';

    if p_id is not null then
        v_sql := v_sql || ' and c.id = $1';
    end if;

    if p_lmt is not null and p_lmt > 0 then
        v_sql := v_sql || format(' limit %s', p_lmt);
    end if;

    if p_id is not null then
        return query execute v_sql using p_id;
    else
        return query execute v_sql;
    end if;
end;
$$;

INSERT INTO crm.contract(
    contract_num, contract_date, contractor_id)
VALUES ('1sdafa1', '5999-12-31', 1);